### ISSUE TITLE
[ios / proofs]: end-to-end proofs in iOS using witnesscalc

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover#232]
# Mission
iOS needs to have a clear end-to-end proof example that goes through AES, HTTP, and JSON to end up outputting an intended value at the end. Right now, iOS does not successfully go through the whole stack.

## Tasks
- [x] Get iOS to use witnesscalc bin files alongside of already loading in R1CS files.
- [x] #240
- [x] Get an example end-to-end proof working on `ios-sim` and an actual `ios` device. 
- [x] Provide rough benchmarks of speed.

## Code Scope
Will touch the following:
- `client_ios` directory

--- 

**Note**: I made an issue from one of these tasks to abandon it from the associated PR.
