### ISSUE TITLE
[wasm / native / proofs]: memory management

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover#233]
# Mission
Currently we are only able to run an old version of AES-GCM in wasm, else we run out of memory. We need to be able to greatly reduce the amount of memory pressure brought in given the collection of circuits. Working to do this in native first is likely a good path for sanity checking.

# Tasks
- [x] Consider: caching only *in use* circuits by the calls to `get_circuit_shapes`. For example, we will likely use AES-GCM for the first $N$ folds, so it is pointless to load in the HTTP or JSON circuits into `PublicParams`. When AES-GCM finishes, we should dealloc the `Vec<R1CSWithArity>` in the `PublicParams` and create a new vec with only the HTTP circuits. It is unclear whether this will "just work" but it is worth a try.
- [ ] Consider: using witnesscalc to compute witness values. It is unclear whether this would impart less memory requirements in the case of wasm, though.
- [ ] Set `profile.release` variables in `Cargo.toml` to increase memory efficiency. This is low hanging fruit, but probably not a massive help.
- [ ] we can switch to slices&'a [...] so then the SetupData<'a> is put onto stack memory. Similarly, we can just create a something along the lines of &'a [r1cs_type1, r1cs_type2, EMPTY, EMPTY] so we only reference circuits in use. This would greatly reduce the amount of memory required. from #234 

## Code Scope
Will touch the following:
- `client_wasm` directory
- `proofs::program::{self, data}`

**WARNING**: Code scope is tentative. More thought is needed!

---
**Example of (1):**
Let's say we are going to run `[AES, AES, ..., AES, HTTP_PARSE, HTTP_LOCK, HTTP_EXTRACT, JSON_PARSE, JSON_EXTRACT, JSON_EXTRACT]` where we call `AES` a total of `N` times. Assume also that `AES` is the 0th index circuit. We can boot up the prover's `PublicParams` with a `Vec<R1CSWithArity>` that is (in pseudocode) `vec![AESR1CSWithArity, Dummy,Dummy,...]` (where `Dummy` is some dummy `R1CSWithArity` that is tiny or even zero-size). Then we can run the first `N` folds, pause the prover, regenerate a new `Vec<R1CSWithArity>` that then contains, say, `HTTP_PARSE`, `HTTP_LOCK`, and `HTTP_EXTRACT`, assuming that this total constraint count leads to a manageable memory alloc from the associated `Vec<R1CSWithArity>`. Continue this until we exhaust the ROM. Conceivably we can have groups of circuits that can be dispatched together. The big chungus circuits are `JSON_PARSE` and `AES` mostly. `JSON_EXTRACT_OBJECT` also could be a bit hectic, but its partner `JSON_EXTRACT_ARRAY_INDEX` is tiny. So those two can likely be dispatched together.

---

Other ideas will likely be needed, but we should certainly attempt the first in the list above.
