### ISSUE TITLE
[proofs]: use new NIVC circuits from `parser-attestor`

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover#237]
# Mission
We currently have hand rolled circuits in `web-prover` made for NIVC that do HTTP parsing/locking/extraction and pass to JSON parsing/extraction. After closing [`parser-attestor/#96`](https://github.com/pluto/parser-attestor/pull/96) we no longer need the circuits HTTP/JSON circuits in `web-prover`. 

## Tasks
- [x] Determine a sane way to bring in the HTTP/JSON NIVC circuits from `parser-attestor`. Currently this is as a node module, but that may not be optimal at all. Indeed, it may be better to create zip file packages with the artifacts or even a simple crate that exposes the files as bytes. Other options of course are there, too.
- [x] Remove the current HTTP/JSON NIVC circuits and their associated artifacts from `web-prover`. 
- [x] Use the new HTTP/JSON NIVC in an end-to-end test natively. 
- [ ] Use these circuits in any other client implementation, e.g., `client-wasm` and `client-ios`, as needed.

## Code Scope
Will touch the following:

- `web_proof_circuits` dir
- `proofs::tests`
- `client_*`

---

Perhaps we don't adjust `client_*` in this PR to reduce scope, though it should not be a large change and depends on order of other issues.
